"""Add checkout_id into Invoice

Revision ID: 6631021fd194
Revises: e04f6b4e73cd
Create Date: 2022-04-19 11:34:49.735499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6631021fd194'
down_revision = 'e04f6b4e73cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('checkout_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'checkout_id')
    # ### end Alembic commands ###
