"""Add checkout_id into Invoice

Revision ID: d90e57d89e31
Revises: e04f6b4e73cd
Create Date: 2022-04-19 07:21:32.353128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd90e57d89e31'
down_revision = 'e04f6b4e73cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('checkout_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'checkout_id')
    # ### end Alembic commands ###
