"""Add invoice state

Revision ID: e04f6b4e73cd
Revises: 28e8ea5e8a58
Create Date: 2022-04-16 20:43:55.699586

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e04f6b4e73cd'
down_revision = '28e8ea5e8a58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE invoicestate_tmp AS ENUM ('not_paid', 'unpaid', 'paid', 'failed')")
    op.execute(
        "ALTER TABLE invoices ALTER COLUMN state SET DATA TYPE invoicestate_tmp USING state::text::invoicestate_tmp"
    )
    op.execute("UPDATE invoices SET state = 'unpaid' WHERE state = 'not_paid'")
    op.execute("DROP TYPE invoicestate")
    op.execute("CREATE TYPE invoicestate AS ENUM ('unpaid', 'paid', 'failed')")
    op.execute(
        "ALTER TABLE invoices ALTER COLUMN state SET DATA TYPE invoicestate USING state::text::invoicestate"
    )
    op.execute("DROP TYPE invoicestate_tmp")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE invoicestate_tmp AS ENUM ('unpaid', 'not_paid', 'paid', 'failed')")
    op.execute(
        "ALTER TABLE invoices ALTER COLUMN state SET DATA TYPE invoicestate_tmp USING state::text::invoicestate_tmp"
    )
    op.execute("UPDATE invoices SET state = 'not_paid' WHERE state = 'unpaid'")
    op.execute("DROP TYPE invoicestate")
    op.execute("CREATE TYPE invoicestate AS ENUM ('not_paid', 'paid', 'failed')")
    op.execute(
        "ALTER TABLE invoices ALTER COLUMN state SET DATA TYPE invoicestate USING state::text::invoicestate"
    )
    op.execute("DROP TYPE invoicestate_tmp")
    # ### end Alembic commands ###
