version: '3.7'

services:
  payment_gateway:
    image: payment_gateway:0.0.1
    build:
      context: ./
      dockerfile: docker/payment_gateway/Dockerfile
    ports:
      - 8001:8000
    env_file:
     - config/.env
    networks:
      - movies-network

networks:
  movies-network:
    external: true
