version: '3.7'

services:
  payment_gateway:
    volumes:
      - ./src/payment_gateway:/opt/payment_gateway

    command: uvicorn --host 0.0.0.0 --port 8000 --reload main:app

  payment_gateway_db:
    ports:
      - 5432:5432

  rabbitmq:
    ports:
      - 5672:5672