swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Payment Gateway for Online movie theater"
host: "127.0.0.1"
basePath: "/api/v1"
schemes:
- "https"
- "http"
paths:
  /invoices:
    post:
      tags:
      - "invoices"
      summary: "Create invoice"
      description: ""
      produces:
      - "application/json"
      security:
      - filmtheater_auth: []
      parameters:
      - in: "body"
        name: "body"
        description: "Created invoice object"
        required: true
        schema:
          type: "object"
          properties:
            product:
              type: "object"
              properties:
                price:
                  type: "object"
                  properties:
                    amount:
                      type: "number"
                    currency:
                      type: "string"
                count:
                  type: "number"
            success_url:
              type: "string"
            fail_url:
              type: "string"
      
      responses:
        "200":
          description: "Invoice created"
          schema:
            type: object
            description: Invoice info
            properties:
              guid:
                type: string
                description: The invoice GUID.
              payment_info:
                type: object
                description: Payment info.
                properties:
                  checkout_url:
                    type: string
        
        "400":
          description: "Somthing wrong"
    
    get:
      tags:
      - "invoices"
      summary: "Get invoices"
      description: ""
      security:
      - filmtheater_auth: []
      responses:
        "200":
          description: "Invoice created"
          schema:
            type: array
            items:
              type: object
              description: Invoice info
              properties:
                guid:
                  type: string
                  description: The invoice GUID.

  /invoices/{InvoiceGUID}/Refund:
    patch:
      tags:
      - "invoices"
      summary: "Change invoice"
      security:
      - filmtheater_auth: []
      parameters:
      - name: "InvoiceGUID"
        in: "path"
        description: GUID of invoice"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Refunding info"
        required: true
        schema:
          type: "object"
          properties:
            invoice_guid:
              type: "string"
            price:
              type: "object"
              properties:
                amount:
                  type: "number"
                currency:
                  type: "string"
      responses:
        "200":
          description: "Invoice refunded"
  
  /payments/{payment_sysytem_id}/Notify:
    post:
      tags:
      - "payments"
      summary: "Payment system notifications webhook"
      parameters:
      - name: "payment_sysytem_id"
        in: "path"
        description: GUID of invoice"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Notification"
        required: true
        schema:
          type: "object"
      responses:
        "200":
          description: "Invoice refunded"
      
  /payments/yookassa/Notify:
    post:
      tags:
      - "payments"
      summary: "Yookassa notifications webhook"
      parameters:
      - in: "body"
        name: "body"
        description: "Notification"
        required: true
        schema:
          type: "object"
          properties:
            type:
              type: "string"
            event:
              type: "string"
            object:
              type: "object"
      responses:
        "200":
          description: "Invoice refunded"
  
  /payments/stripe/webhook:
    post:
      tags:
      - "payments"
      summary: "Stripe notifications webhook"
      parameters:
      - in: "body"
        name: "body"
        description: "Notification"
        required: true
        schema:
          type: "object"
      responses:
        "200":
          description: "Invoice refunded"

securityDefinitions:
  filmtheater_auth:
    type: "apiKey"
    name: "Authorization"
    in: "header"

      