@startuml

skinparam component {
    backgroundColor<<new>> #438dd5
    backgroundColor<<dev>> #8577a0
    backgroundColor<<existing>> #85bbf0
    backgroundColor<<external>> #85fff0
}

component "ЛK" as CinemaPaymentServiceClient <<existing>>

component "Сервис авторизации" as AuthService <<dev>>

component SynemaPaymentSystem {
    component PaymentGateway <<new>>
    note bottom of PaymentGateway
        Инкапсулирует работу
        с платежными сервисами
    end note

    database PaymentGatewayDb
    PaymentGateway <-down-> PaymentGatewayDb

    component InvoiceStatesQueue <<new>>
    note bottom of InvoiceStatesQueue
        RabbitMQ
    end note
}

component "Платежная система" as PaymentSystem <<external>>
note bottom of PaymentSystem
    Это могут быть
    1. http://pay.yandex.ru
    2. https://yookassa.ru/
    3. https://stripe.com/
    ...
end note


component "Сервис нотификации" as NotificationService <<existing>>

CinemaPaymentServiceClient --> AuthService: Создать запрос на покупку подписки

PaymentGateway <--> PaymentSystem
PaymentGateway -right-> NotificationService: Оплата зафиксирована

PaymentGateway -left-> InvoiceStatesQueue: Сообщение об изменении статуса

AuthService -down-> PaymentGateway: Создать инвойс
AuthService -left-> InvoiceStatesQueue: Получить статус инвойса
AuthService --> NotificationService: Сообщить что подписка скоро истекает

@enduml
